---
- name: failed demo
  hosts: lamp
  tasks:
    - name: do something that fails
      lvol:
        lv: lvnoting
        vg: vgnothing
        size: 1G
      register: command_result
      ignore_errors: yes
    - name: show command result error
      debug:
        var: command_result
    - name: pring an understandable message
      fail:
        msg: "volume group does not exits"
      when: "'Failed' in command_result.msg"
