---
- name: deploy vsftpd
  hosts: development
  tasks:
  - name: install vsftpd
    yum: name=vsftpd
  - name: enable vsftpd
    service: name=vsftpd enabled=true
  - name: create readme file
    copy:
      content: "this is a readme file"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444
...
