---
- name: enable webserver
  hosts: development
  become: yes  # Ensure tasks run with elevated privileges
  tasks:
    - name: install httpd and firewalld
      yum:
        name:
          - httpd
          - firewalld
        state: latest

    - name: install welcome page
      copy:
        content: "Welcome to the webpage"
        dest: /var/www/html/index.html

    - name: start web-server
      service:
        name: httpd
        enabled: true
        state: started

    - name: start firewalld service
      service:
        name: firewalld
        enabled: true
        state: started

    - name: open firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

- name: test web server access
  hosts: localhost
  become: no
  tasks:  # <- Fixed indentation here
    - name: connect to the web server
      uri:
        url: http://13.60.199.181
        return_content: yes
        status_code: 200
...
