---
- name: configure vsftpd using tempalte
  hosts: lamp
  vars:
    anonymous_enabeled: yes
    local_enabled: yes
    write_enabled: yes
    anon_upload_enabled: yes
  tasks:
  - name: install vstfpd
    yum:
      name: vsftpd
  - name:use template to copy ftp configuration
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf
      
