---
- name: multipe conditions demo
  hosts: lamp
  tasks:
  - name: install httpd
    package:
      name: httpd
      state: removed
    when: >
      ( ansible_destribution == "RedHat" and
        ansible_memfree_mb > 512)
      or
      ( ansible_destribution == "CentOS" and
        ansible_memfree_mb > 1024)
