---
- name: register command
  hosts: lamp
  tasks:
  - shell: cat /etc/passwd
    register: passwd_contents
  - debug:
      msg: echo "passwd contains user chaitanya"
    when: passwd_contents.stdout.find('chaitanya') != -1
